from routers import auth
from routers.stocks import core_stocks
from routers.forex import forex
from routers.cryptocurrencies import crypto
from routers.commodities import commodities
from routers.economic_indicators import economic_indicators
from routers.news_insights import news_insights
from routers.codes import get_codes
from routers.technical_indicators import technical_indicators
from routers import ekyc
from routers.admin import pricing
from routers.payments import stripe
from routers.users import userAdditionalData
